dist: trusty
language: generic
services: docker
sudo: required

matrix:
  include:
    - env: TARGET=aarch64-unknown-linux-gnu
      os: linux
    - env: TARGET=arm-unknown-linux-gnueabi
      os: linux
    - env: TARGET=arm-unknown-linux-gnueabihf
      os: linux
    - env: TARGET=armv7-unknown-linux-gnueabihf
      os: linux
    - env: TARGET=i586-unknown-linux-gnu
      os: linux
    - env: TARGET=i686-apple-darwin
      language: ruby
      os: osx
    - env: TARGET=i686-unknown-linux-gnu
      os: linux
    - env: TARGET=mips-unknown-linux-gnu
      os: linux
    - env: TARGET=mipsel-unknown-linux-gnu
      os: linux
    - env: TARGET=powerpc-unknown-linux-gnu
      os: linux
    - env: TARGET=powerpc64-unknown-linux-gnu
      os: linux
    - env: TARGET=powerpc64le-unknown-linux-gnu
      os: linux
    - env: TARGET=thumbv6m-none-eabi
      os: linux
    - env: TARGET=thumbv6m-none-eabi WEAK=true
      os: linux
    - env: TARGET=thumbv7em-none-eabi
      os: linux
    - env: TARGET=thumbv7em-none-eabi WEAK=true
      os: linux
    - env: TARGET=thumbv7em-none-eabihf
      os: linux
    - env: TARGET=thumbv7em-none-eabihf WEAK=true
      os: linux
    - env: TARGET=thumbv7m-none-eabi
      os: linux
    - env: TARGET=thumbv7m-none-eabi WEAK=true
      os: linux
    - env: TARGET=x86_64-apple-darwin
      language: ruby
      os: osx
    - env: TARGET=x86_64-unknown-linux-gnu
      os: linux

install:
  - bash ci/install.sh

script:
  - bash ci/script.sh

branches:
  only:
    - auto
    - try

notifications:
  email:
    on_success: never
  webhooks: https://homu.herokuapp.com/travis
