environment:
  matrix:
    - TARGET: i686-pc-windows-msvc
    - TARGET: x86_64-pc-windows-msvc

install:
  - git submodule update --init
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe --default-host x86_64-pc-windows-msvc --default-toolchain nightly -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - if "%TARGET%"=="i686-pc-windows-msvc" ( rustup target add %TARGET% )
  - rustc -Vv
  - cargo -V

build: false

test_script:
  - cargo build --target %TARGET% --example intrinsics
  - cargo build --release --target %TARGET% --example intrinsics
  - cargo test --no-default-features --features gen-tests --target %TARGET%
  - cargo test --no-default-features --features "gen-tests c" --target %TARGET%
  - cargo test --no-default-features --features gen-tests --release --target %TARGET%
  - cargo test --no-default-features --features "gen-tests c" --release --target %TARGET%
