environment:
  matrix:
    - TARGET: i686-pc-windows-msvc
    - TARGET: x86_64-pc-windows-msvc

install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.exe"
  - rust-nightly-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - rustc -Vv
  - cargo -V

build: false

test_script:
  - cargo build
  - cargo build --release
  - cargo test
  - cargo test --release
  - CALL "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"
  - dumpbin /disasm target/debug/librustc_builtins.rlib || exit 0
  - dumpbin /disasm target/release/librustc_builtins.rlib || exit 0

branches:
  only:
    - master
