trigger:
  - master

jobs:
  # - job: Linux
  #   pool:
  #     vmImage: ubuntu-16.04
  #   steps:
  #     - template: ci/azure-steps.yml
  #   strategy:
  #     matrix:
  #       aarch64:
  #         TARGET: aarch64-unknown-linux-gnu
  #       arm:
  #         TARGET: arm-unknown-linux-gnueabi
  #       armhf:
  #         TARGET: arm-unknown-linux-gnueabihf
  #       i586:
  #         TARGET: i586-unknown-linux-gnu
  #       i686:
  #         TARGET: i686-unknown-linux-gnu
  #       mips:
  #         TARGET: mips-unknown-linux-gnu
  #       mips64:
  #         TARGET: mips64-unknown-linux-gnuabi64
  #       mips64el:
  #         TARGET: mips64el-unknown-linux-gnuabi64
  #       mipsel:
  #         TARGET: mipsel-unknown-linux-gnu
  #       powerpc:
  #         TARGET: powerpc-unknown-linux-gnu
  #       powerpc64:
  #         TARGET: powerpc64-unknown-linux-gnu
  #       powerpc64le:
  #         TARGET: powerpc64le-unknown-linux-gnu
  #       thumbv6m:
  #         TARGET: thumbv6m-linux-eabi
  #         XARGO: 1
  #       thumbv7em:
  #         TARGET: thumbv7em-linux-eabi
  #         XARGO: 1
  #       thumbv7emhf:
  #         TARGET: thumbv7em-linux-eabihf
  #         XARGO: 1
  #       thumbv7m:
  #         TARGET: thumbv7m-linux-eabi
  #         XARGO: 1
  #       wasm32:
  #         TARGET: wasm32-unknown-unknown
  #         ONLY_BUILD: 1
  #       x86_64:
  #         TARGET: x86_64-unknown-linux-gnu
  #
  # - job: macOS
  #   pool:
  #     vmImage: macos-10.13
  #   steps:
  #     - template: ci/azure-steps.yml
  #   strategy:
  #     matrix:
  #       x86_64:
  #         TARGET: x86_64-apple-darwin
  #       i686:
  #         TARGET: i686-apple-darwin
  #
  - job: Windows
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - template: ci/azure-steps.yml
    strategy:
      matrix:
        i686-msvc:
          TARGET: i686-pc-windows-msvc
        x86_64-msvc:
          TARGET: x86_64-pc-windows-msvc
        i686-gnu:
          TARGET: i686-pc-windows-gnu
        x86_64-gnu:
          TARGET: x86_64-pc-windows-gnu
