[package]
authors = ["Jorge Aparicio <japaricious@gmail.com>"]
build = "build.rs"
name = "compiler_builtins"
version = "0.1.0"

[build-dependencies]
rand = "0.3.15"

[build-dependencies.gcc]
optional = true
version = "0.3.36"

[target.'cfg(all(target_arch = "arm", not(any(target_env = "gnu", target_env = "musl")), target_os = "linux"))'.dev-dependencies]
test = { git = "https://github.com/japaric/utest" }
utest-cortex-m-qemu = { git = "https://github.com/japaric/utest", default-features = false }
utest-macros = { git = "https://github.com/japaric/utest" }

[features]
c = ["gcc"]
compiler-builtins = []
default = ["compiler-builtins"]
mem = []
rustbuild = ["compiler-builtins"]

[workspace]
