[package]
authors = ["Jorge Aparicio <japaricious@gmail.com>"]
build = "build.rs"
name = "rustc_builtins"
version = "0.1.0"

[dependencies]

[dependencies.rlibc]
git = "https://github.com/alexcrichton/rlibc"
optional = true

[dev-dependencies]
quickcheck = "0.3.1"
rand = "0.3.14"
gcc_s = { path = "gcc_s" }
compiler-rt = { path = "compiler-rt" }

[features]
weak = ["rlibc/weak"]

[workspace]
