[package]
name = "cb"
version = "0.1.0"
authors = ["Jorge Aparicio <jorge@japaric.io>"]
edition = "2021"
publish = false

[lib]
test = false
bench = false

[features]
# Duplicated from libm's Cargo.toml
unstable = []
unstable-intrinsics = []
checked = []
force-soft-floats = []
