[package]
name = "profiler_builtins"
version = "0.0.0"
edition = "2021"

[lib]
test = false
bench = false
doc = false

[dependencies]

[build-dependencies]
# FIXME: Pinned due to build error when bumped (#132556)
cc = "=1.1.22"
